# Generated by Django 5.2.4 on 2025-08-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='notification_method',
            field=models.CharField(choices=[('email', 'Email'), ('console', 'Console Notification')], default='email', max_length=10),
        ),
    ]
