# Generated by Django 5.2.4 on 2025-08-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='sector',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='industry',
        ),
    ]
